swagger: '2.0'

info:
  version: "0.0.0"
  title: Integrasjonspunkt receipt API
  
basePath: /
produces:
  - application/json

paths:
  /conversations:
    get:
      description:
        Gets a list of all conversations
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/conversation'
  /conversations/{convId}:
    get:
      description:
        Get conversation with given id
      parameters:
        - name: convId
          in: path
          description: valid id of a conversation
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/conversation'
        404:
          description: Not found
  /statuses:
    get:
      description:
        Get a list of all statuses
      parameters:
        - name: fromId
          in: query
          description: Gets all statuses with given serial number and higher
          required: false
          type: integer
        - name: convId
          in: query
          description: Filter on conversation id
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/status'
  /statuses/{statId}:
    get:
      description:
        Get status with given id
      parameters:
        - name: statId
          in: path
          description: valid id of a status
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/status'
        400:
          description: Not found
  /statuses/peek:
    get:
      description:
        Get latest status
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/status'
        204:
          description: No content

definitions:
  status:
    type: object
    properties:
      statId:
        type: integer
        description: Id
      convId:
        type: integer
        description: Conversation id
      lastUpdate:
        type: string
        description: ISO 8601 timestamp of last update
      status:
        type: string
        description: Status value
      description:
        type: string
        description: Additional status information
      rawReceipt:
        type: string
        description: Raw receipt (if supplied)
  conversation:
    type: object
    properties:
      convId:
        type: string
        description: Id
      conversationId:
        type: string
        description: Conversation id of message
      receiverIdentifier:
        type: string
        description: Identifier of receiver
      messageReference:
        type: string
        description: Message reference
      messageTitle:
        type: string
        description: Message title
      lastUpdate:
        type: string
        description: ISO 8601 timestamp of status
      serviceIdentifier:
        type: string
        description: Service identifier of message (DPO, DPV, DPI etc)
      messageStatuses:
        type: array
        items:
          $ref: '#/definitions/status'